New week
Offmat/puzzle_room pull request #6
Opened 2018-02-03 14:10 UTC by Offmat

2018-02-03 22:25 UTC, fanfilmu requested changes
A, dla odmiany. Za tego selecta masz Request changes.

![i](https://media.giphy.com/media/DfdbTJZx6Yjra/200w_d.gif)

2018-02-03 22:25 UTC, fanfilmu commented on app/views/comments/_form.html.erb
> +  <%= form_for [@comment] do |f| %>
Można by bez `[]`

2018-02-03 22:25 UTC, fanfilmu commented on app/views/comments/_form.html.erb
> +    <%= f.hidden_field :commentable_type, value: model.class.to_s %>
Rozumiem że Railsy nie są _aż tak_ mądre żeby `hidden_field :commentable, value: model` zadziałało? :D nie wiem nawet, szczerze mówiąc, ale raczej nie

2018-02-03 22:25 UTC, fanfilmu commented on app/controllers/puzzles_controller.rb
> +    if params[:q].present?
[`#dig`](http://api.rubyonrails.org/classes/ActionController/Parameters.html#method-i-dig). I trochę sprytu ;)

```ruby
@puzzles = Puzzle.all.order(:name)
material_id = params.dig(:q, :material_id)&.to_i
@puzzles = @puzzles.joins(:materials).where(materials: { id: material_id }) if material_id.present?
```

Powinno działać, chyba. Pamiętaj, zawsze lepiej query robić niż `#select` - select jest już Ruby'owy więc na pewno wolniejszy niż query w bazie.

2018-02-03 22:25 UTC, fanfilmu commented on app/controllers/comments_controller.rb
> +    @comment = Comment.new(user: current_user)
Może być, albo jak Ci się bardziej spodoba:

```ruby
Comment.new(comment_params.merge(user: current_user))
```

2018-02-03 22:25 UTC, fanfilmu commented on app/controllers/application_controller.rb
> +  def find_lua(object)
Zdaje się, że (przynajmniej na razie) korzystasz z tego tylko w `CommentsController` - skoro tak, to raczej tam powinna być ta metoda

2018-02-03 22:25 UTC, fanfilmu commented on app/controllers/application_controller.rb
> +  helper_method :find_lua
Używasz tego w widokach? Jeśli nie, to nie ma co udostępniać im tej metody

2018-02-04 12:24 UTC, Offmat commented on app/controllers/comments_controller.rb
> +    @comment = Comment.new(user: current_user)
Zdecydowanie bardziej mi się podoba:)

2018-02-04 14:46 UTC, fanfilmu approved these changes
![i](https://media.giphy.com/media/10AmJ6TIlbYxAk/giphy-downsized.gif)

2018-02-04 15:09 UTC, closed without merging